{"errorMessage": "Athena FAILED. QID=bbee2999-78a0-4ee6-9ae7-1ad3e0760372. Reason=Insufficient permissions to execute the query. User: arn:aws:sts::050451385876:assumed-role/MedlaunchEltStack-AthenaRunnerFnServiceRole7A12EDBC-mqJu1fu1vlMr/MedlaunchEltStack-AthenaRunnerFn6D1FF706-vbuF8A8V4BOM is not authorized to perform: glue:GetPartition on resource: arn:aws:glue:us-east-1:050451385876:catalog because no identity-based policy allows the glue:GetPartition action . If a data manifest file was generated at 's3://medlaunch-elt-datalake-050451385876-us-east-1/stage3-athena-query-results/_scratch/bbee2999-78a0-4ee6-9ae7-1ad3e0760372-manifest.csv', you may need to manually clean the data from locations specified in the manifest. Athena will not delete data in your account.", "errorType": "RuntimeError", "requestId": "49441f0e-0b73-4908-bb43-13ddc13e310a", "stackTrace": ["  File \"/var/task/handler.py\", line 325, in handler\n    run_athena(INSERT_PROCESSED, context.get_remaining_time_in_millis())\n", "  File \"/var/task/handler.py\", line 141, in run_athena\n    raise RuntimeError(f\"Athena {state}. QID={qid}. Reason={reason}\")\n"]}